export const CAREERS = [
  {
    position: "Frontend Enginner",
    company: "PT Ismaya Group",
    logo: "https://res.cloudinary.com/dlwlhvdms/image/upload/v1695283828/portfolio/logoismaya_fb5lit.png",
    location: "Jakarta Selatan",
    location_type: "Hybrid",
    type: "Freelance",
    start_date: "2023-08",
    end_date: null,
    link: "https://www.ismaya.com/",
  },
  {
    position: "Frontend Developer",
    company: "PT Jasa Kelola Asia",
    logo: "https://res.cloudinary.com/dlwlhvdms/image/upload/v1695283719/portfolio/jatislogo_iewjnq.png",
    location: "Jakarta Selatan",
    location_type: "On Site",
    type: "Fulltime",
    start_date: "2022-12",
    end_date: "2023-08",
    link: "https://jatisservice.com/",
  },
  {
    position: "Application Developer",
    company: "PT Mitra Integrasi Informatika",
    logo: "https://res.cloudinary.com/dlwlhvdms/image/upload/v1695283409/portfolio/miilogo_up2nfp.png",
    location: "Jakarta Barat",
    location_type: "On Site",
    type: "Fulltime",
    start_date: "2020-12",
    end_date: "2022-12",
    link: "https://www.mii.co.id/",
  },
  {
    position: "Backend Developer",
    company: "PT Visionet Data Internasional",
    logo: "https://res.cloudinary.com/dlwlhvdms/image/upload/v1695283115/portfolio/visionetlogo_x8jne9.png",
    location: "Tangerang",
    location_type: "On Site",
    type: "Internship",
    start_date: "2019-09",
    end_date: "2020-04",
    link: "https://www.visionet.co.id/id/beranda/",
  },
];
